"""Create userExpense table

Revision ID: 202f131e1971
Revises: d9a8bc0b96d6
Create Date: 2024-09-16 17:55:58.202004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202f131e1971'
down_revision = 'd9a8bc0b96d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_expense')
    # ### end Alembic commands ###
